### ISSUE TITLE
Create a build pipeline for the docker image

### ISSUE THREAD

**Issue by gat786** [TesseractCoding/Ric-Bot#1]
A build pipeline will help in building the docker image automatically and will ease deployment process.

**Comment by anushkrishnav** [comment]
Might help 
https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/containers/build-image?view=azure-devops

**Comment by gat786** [comment]
Thanks, Anush :-)
We are using GitHub actions as much as possible this time around. To make things as much as open as possible.

**Comment by gat786** [comment]
Latest commit includes docker build and push to dockerhub action.
