### ISSUE TITLE
Add `data` layer to save context

### ISSUE THREAD

**Issue by gat786** [TesseractCoding/Ric-Bot#21]
This layer will be at level of modules. But it will be there to store and retrieve data from SQLite databases according to the server on which the bot is running. These databases will be small and only store limited amount of data.

**Comment by ricardoprins** [comment]
This also raises another need - the bot needs to check the availability of the SQL connection prior to its start - it should return some sort of error if the connection isn't available.

The same should be done for each of our APIs, actually (Reddit, and any other we use in the future)

**Comment by ricardoprins** [comment]
I'll take this one.
