### ISSUE TITLE
Create an advanced quotes handler.

### ISSUE THREAD

**Issue by gat786** [TesseractCoding/Ric-Bot#23]
This handler should intelligently provide quotes from a large corpus of quotes. This can filter out quotes on based topics such as inspiration/motivation, positivity, humanity etc. 

I would be happy to be see an implementation where the corpus is not stored on our repository but some where in a blob storage and this handler works with it. But if needed we can also keep it in the codebase. It will just make it bigger so need to make proper decisions.

**Comment by gat786** [comment]
Best of luck ricardo!

**Comment by ricardoprins** [comment]
Thankies!
