### ISSUE TITLE
Create a web interface to customize options

### ISSUE THREAD

**Issue by gat786** [TesseractCoding/Ric-Bot#25]
This can include a generated site which gets hosted on port:80 when the container is running and can have options to change for the bot.

**Comment by ricardoprins** [comment]
Amazing idea. I can work on the backend of this, if someone wants to take the design part, it would be great.

**Comment by gat786** [comment]
This will be a big old monolithic since it will only change the properties of its own docker image. We can change options such as which channels are allowed to have promotions in it. It can also help in setting different settings for the bot.

**Comment by ricardoprins** [comment]
We can also add which roles can post links, and things like that - shifting from channels to roles is imo the solution to our problem in the antispam module btw
