### ISSUE TITLE
Create a different Github action for PR's which checks Linting and docker build

### ISSUE THREAD

**Issue by gat786** [TesseractCoding/Ric-Bot#27]
This action will only run-on PR's and will check code quality as well as the successful creation of a docker image. It should not push it to any registry just check that it builds without any issues.

**Comment by gat786** [comment]
Latest commit includes a linting action for prs. Working on something for building an image

**Comment by anushkrishnav** [comment]
I will set up python linter actions

**Comment by gat786** [comment]
Pylint action already exists. You can see on how to better represent it. Like currently however the result maybe all of the runs pass. We need to have a barrier for passing. Also check if you can implement docker build action. For building the command is already present in the readme.
