### ISSUE TITLE
Move to functional types of bot commands

### ISSUE THREAD

**Issue by gat786** [TesseractCoding/Ric-Bot#28]
Discord.py has extensions with which you can make commands which will ease the complexity of commands.py. [This](https://discordpy.readthedocs.io/en/latest/ext/commands/extensions.html) is a good starting point to know more about its implementation

**Comment by ricardoprins** [comment]
We need the option for privileged intents to be enabled for our bot to work with the full power and might of discord.py

https://discordpy.readthedocs.io/en/stable/intents.html

**Comment by adnan007d** [comment]
I can take this, I will use cogs.
