### ISSUE TITLE
Remove NSFW memes coming from the Reddit Sources. 

### ISSUE THREAD

**Issue by gat786** [TesseractCoding/Ric-Bot#3]
While the sources are picked to be SFW some occurrences have been seen where a NSFW meme gets shared by the bot. It will be best if we handpick the `subreddits` or sources from which we are fetching memes and make them so that they mostly return SFW content.

**Comment by gat786** [comment]
@anushkrishnav I'm hoping you can easily take care of this. no need to add ML things at first. We can do with just finetuning the selection of subreddits I guess and then ML can be added at a later stage.

**Comment by anushkrishnav** [comment]
> @anushkrishnav I'm hoping you can easily take care of this. no need to add ML things at first. We can do with just finetuning the selection of subreddits I guess and then ML can be added at a later stage.

Okay @gat786 I will go on a wild subreddit hunt to find the purest form of memes. Wish me luck

**Comment by anushkrishnav** [comment]
@gat786  
I will share the subreddits here for approval 
1 - https://www.reddit.com/r/sfwmemes/

**Comment by gat786** [comment]
2. https://reddit.com/r/memes
3. https://reddit.com/r/wholesomememes
4. https://reddit.com/r/BikiniBottomTwitter

**Comment by ricardoprins** [comment]
> @gat786
> I will share the subreddits here for approval
> 1 - https://www.reddit.com/r/sfwmemes/

Added to the updated code to be released in the next version

**Comment by ricardoprins** [comment]
> 1. https://reddit.com/r/memes
> 2. https://reddit.com/r/wholesomememes
> 3. https://reddit.com/r/BikiniBottomTwitter

Added as well

**Comment by anushkrishnav** [comment]
> > @gat786
> > I will share the subreddits here for approval
> > 1 - https://www.reddit.com/r/sfwmemes/
> 
> Added to the updated code to be released in the next version

Are you working on the issue ?

**Comment by ricardoprins** [comment]
Yes, but only in the implementation side. This is the current list of subreddits that are being used in the API, please let me know if I should remove any.

As a means of informing how the algorithm works, it basically extracts a random meme between the last 21 posted in all the subreddit set.

The list:
- r/funnyterriblefacebookmemes
- r/ProgrammerHumor
- r/MemeEconomy
- r/memes (already checked)
- r/dankmemes
- r/AdviceAnimals
- r/sfwmemes (already checked)
- r/BikiniBottomTwitter(already checked)
- r/wholesomememes (already checked)

**Comment by gat786** [comment]
`/dankmemes` should be removed `/programmerhumor` can work I guess lemme check others

**Comment by ricardoprins** [comment]
Any other should be added or removed? I'm thinking we can close this issue if we don't have anything else...unless we wanna use ML to filter the images once they're selected by the algorithm

**Comment by gat786** [comment]
For now it seems good :-)

**Comment by ricardoprins** [comment]
Closing this for now.
