### ISSUE TITLE
Anti Spam can be bypassed

### ISSUE THREAD

**Issue by adnan007d** [TesseractCoding/Ric-Bot#34]
https://www.mysupersecretwebsite.com/?bypassed=https://github.com/
https://www.youtube.com/?bypassed=https://github.com/

Get parameters doesn't hurt the request made so adding github.com in it, can bypass the antispam

**Comment by ricardoprins** [comment]
Nice! Do we have a way of avoiding it? I'm gonna do some research later today

**Comment by adnan007d** [comment]
I guess rather than using in operator we can use startsWith()

**Comment by gat786** [comment]
That seems like a good idea. I have assigned you this task @adnan007d lemme know if you face problems while clearing this out.

**Comment by adnan007d** [comment]
Merged Successfully
