### ISSUE TITLE
[Feature] Fetching Random Quotes

### ISSUE THREAD

**Issue by KamalDGRT** [TesseractCoding/Ric-Bot#35]
### Objective :pushpin:

To get a random quote using an API instead of hard-coded values.

**Comment by gat786** [comment]
Seems like a good idea. Do you think you can help us with this implementation?

**Comment by KamalDGRT** [comment]
Yes. I would love to!

**Comment by KamalDGRT** [comment]
I will create the PR by tomorrow. 
I have tested it out in my server with a different logic.
