### ISSUE TITLE
[Doc] Add Contributing Guidelines

### ISSUE THREAD

**Issue by KamalDGRT** [TesseractCoding/Ric-Bot#39]
### AIM

Create Contributors Guideline to help new Contributors get started with this Project.

#### Features

- Add a `CONTRIBUTING.md` to let the new users gain insight on how to get started with the project and how to contribute to the same.
- Add Screenshots wherever possible.
- Mention the way to set the project locally in the PC
- Add the basic information about creating Issues, Pull Requests and Branching.
- Mention tutorials related to Git and GitHub to help them better understand.

**Comment by gat786** [comment]
I will take this one. And make a guidelines document.

**Comment by KamalDGRT** [comment]
Okayy :+1:
