### ISSUE TITLE
Remove dependency of directly reading secrets from modules to get_secret.py

### ISSUE THREAD

**Issue by gat786** [TesseractCoding/Ric-Bot#5]
While we can read environment secrets from any python file it will be much modular if we had a single function or class with which we can access all the environment variables. The current file for doing so is `get_secrets.py` which can be updated to do so.

**Comment by ricardoprins** [comment]
We can have an async function that runs with a dependency from get_secrets.py(which can also be renamed imo) - a function that loads the env variables.
