### ISSUE TITLE
Refactoring code for secrets configuration

### ISSUE THREAD

**Issue by ricardoprins** [TesseractCoding/Ric-Bot#6]
In order to better standardize things, I think that the get_secrets.py file should be moved into the modules folder, and it should follow the same standard, so that the main folder only contains the main file.

Any thoughts? I'll do this in my fork so you guys can take a look

**Comment by anushkrishnav** [comment]
But why ?

**Comment by ricardoprins** [comment]
TL,DR: Just putting each thing in its own box, basically.

Cleaner and more logical, assuming that it is in theory a module. In fact, what I'll propose in my next PR is a bigger revamping - a settings module that will hold all the internal configs in the background, with other additional modules being added for holding separated tasks such as anti-spam control, memes, events, and other stuff - these all will be independent from the connection/basic setup tasks, only holding information regarding the aforementioned tasks (anti-spam control module, for example, will only have specific stuff regarding anti-spam control and so on).
