### ISSUE TITLE
Deleting Promotional links posted by members

### ISSUE THREAD

**Issue by anushkrishnav** [TesseractCoding/Ric-Bot#7]
I propose this feature to stop new joining members from posting any links as they can be potential spam or NSFW content.
We can allow members who have a certain tag that they earn after being active for a while of given to them by a mod that will allow them to post a link.
Until then if the new members wish to share anything they can approach a "mod" or "Member"  to share anything that can be useful.
But We can let people post links that starts with https://github.com/

**Comment by ricardoprins** [comment]
I am writing down a basic skeleton for a link-blocking feature. Let's see if we can improve it in the next version. I'll probably be uploading a major update in a day or two here.

**Comment by anushkrishnav** [comment]
I am working on the feature if you can make a small skeleton for this I can spend more time on it
