### ISSUE TITLE
Flag offensive words

### ISSUE THREAD

**Issue by anushkrishnav** [TesseractCoding/Ric-Bot#8]
Mods cant be present and monitor chat always so I propose we use the bot to flag offensive works to make the space more inclusive
1) Use this as an initial database https://www.cs.cmu.edu/~biglou/resources/bad-words.txt
2) create our own database where we can add words to the list by a certain command '\censor word'

The bot will have permission to delete the message and issue a warning against use of such word in the community.

**Comment by ricardoprins** [comment]
Dude, have you checked this list? 'Africa' and 'arab' are listed as bad words...What the heck?

We could check to see if there are some other bots out there that can give us inspiration on how to implement this effectively.

**Comment by anushkrishnav** [comment]
> Dude, have you checked this list? 'Africa' and 'arab' are listed as bad words...What the heck?
> 
> We could check to see if there are some other bots out there that can give us inspiration on how to implement this effectively.

This list is not accurate and I will be personally going through every word once before I implement it.

**Comment by ricardoprins** [comment]
I was thinking that instead of flagging individual words, we could have the bot run messages through an API that verifies if they are offensive or not.

**Comment by adnan007d** [comment]
Found this https://github.com/turalus/encycloDB/blob/master/Dirty%20Words/DirtyWords.json

**Comment by gat786** [comment]
This looks like a good set of words to begin with.

**Comment by adnan007d** [comment]
I can implement this with the given set of words

**Comment by ricardoprins** [comment]
Something that should be brought into consideration is that words per se aren't offensive...

We could maintain a minimum list of words that should, upon usage, generate a warning to the user - and some sort of three strikes system. 

Otherwise, we may risk committing errors in censoring words outside of their context...

That being said, if some sort of filtering is to be implemented that considers offensive usage, it should necessarily use some sort of sentiment analysis - it has to be a ML solution, or it risks being flawed.

**Comment by gat786** [comment]
Yep when the strikes are over moderators can look up the task.

**Comment by anushkrishnav** [comment]
> Something that should be brought into consideration is that words per se aren't offensive...
> 
> We could maintain a minimum list of words that should, upon usage, generate a warning to the user - and some sort of three strikes system.
> 
> Otherwise, we may risk committing errors in censoring words outside of their context...
> 
> That being said, if some sort of filtering is to be implemented that considers offensive usage, it should necessarily use some sort of sentiment analysis - it has to be an ML solution, or it risks being flawed.

We can go with [Azure Content Moderator](https://azure.microsoft.com/en-in/services/cognitive-services/content-moderator/) 
Or build a profanity filter ourselves maybe as another project in TC. 
We can use hate speech dataset from Twitter, Facebook etc too 
This [article](https://towardsdatascience.com/building-a-better-profanity-detection-library-with-scikit-learn-3638b2f2c4c2) would be a good place to start

**Comment by ricardoprins** [comment]
I like the idea of using Azure Content Moderator!

**Comment by anushkrishnav** [comment]
We might run out of free tier calls or credits as we move further but I think we can go with azure for now and build an in-house classifier and improve it.

**Comment by ricardoprins** [comment]
yeah, just to have the feature running initially, and then we can brainstorm on how to build it ourselves. 

how many free calls do we have?

**Comment by anushkrishnav** [comment]
Pricing details : https://azure.microsoft.com/en-us/pricing/details/cognitive-services/content-moderator/

**Comment by gat786** [comment]
We can start by selecting a few words which are bound to be slurs and put it in a map which when found in a message and we can either mark it as [spoiler](https://support.discord.com/hc/en-us/articles/360022320632-Spoiler-Tags-) or delete that message and raise a message saying it is not allowed.

**Comment by ricardoprins** [comment]
that's a good way of having the feature kickstarted.

**Comment by adnan007d** [comment]
I'll implement this with some selected words
